spring:
  application:
    name: Insurance-Management-System
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      name: supervisor
      password: superPassword
logging:
  file:
    path: ./logback
    name: application.log



